import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.ui import Select
from selenium.webdriver import ActionChains
from selenium.webdriver.common.alert import Alert
import pytest

def test_01():
    service = ChromeService(executable_path=ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    driver.implicitly_wait(5)
    driver.get("https://opensource-demo.orangehrmlive.com/")
    driver.implicitly_wait(5)
    time.sleep(3)
    driver.maximize_window()
    time.sleep(3)
    driver.find_element(By.NAME,"username").send_keys("Admin")
    driver.implicitly_wait(5)
    driver.find_element(By.NAME,value="password").send_keys("admin123")
    driver.implicitly_wait(5)
    driver.find_element(By.XPATH,value="//button[@type='submit']").click()
    time.sleep(5)

def test_02():
    service = ChromeService(executable_path=ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    driver.get("https://opensource-demo.orangehrmlive.com/")
    time.sleep(3)
    driver.maximize_window()
    time.sleep(3)
    driver.implicitly_wait(10)
    Username = "Admin"
    Password = "bdmin123"
    driver.find_element(By.NAME, value="username").send_keys(Username)
    driver.implicitly_wait(10)
    driver.find_element(By.NAME, value="password").send_keys(Password)
    driver.implicitly_wait(10)
    driver.find_element(By.XPATH, value="//button[@type='submit']").click()
    time.sleep(5)
    if Password != "admin123":
        print("Invalid Password")

def test_03():
    service = ChromeService(executable_path=ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    driver.get("https://opensource-demo.orangehrmlive.com/")
    time.sleep(3)
    driver.maximize_window()
    time.sleep(3)
    driver.find_element(By.NAME, value="username").send_keys("Admin")
    time.sleep(2)
    driver.find_element(By.NAME, value="password").send_keys("admin123")
    time.sleep(2)
    driver.find_element(By.XPATH, value="//button[@type='submit']").click()
    time.sleep(4)
    driver.find_element(By.LINK_TEXT,value="PIM").click()
    time.sleep(3)
    driver.find_element(By.LINK_TEXT,value="Add Employee").click()
    time.sleep(5)
    driver.find_element(By.NAME,"firstName").send_keys("Sarala")
    time.sleep(1)
    driver.find_element(By.NAME, "middleName").send_keys("Gunasekaran")
    time.sleep(1)
    driver.find_element(By.NAME,"lastName").send_keys("Karky")
    time.sleep(1)
    driver.find_element(By.XPATH,"//div//label//span[@class='oxd-switch-input oxd-switch-input--active --label-right']").click()
    time.sleep(2)
    driver.find_element(By.XPATH,'(//div//input[@class="oxd-input oxd-input--active"])[3]').send_keys("sarala")
    time.sleep(2)
    driver.find_element(By.XPATH, '(//div//input[@class="oxd-input oxd-input--active" and @type="password"])[1]').send_keys("Qwerty@123")
    time.sleep(2)
    driver.find_element(By.XPATH, '(//div//input[@type="password"])[2]').send_keys("Qwerty@123")
    time.sleep(5)
    driver.find_element(By.XPATH,"//button[@type='submit']").click()
    time.sleep(5)

def test_04():
    service = ChromeService(executable_path=ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    driver.get("https://opensource-demo.orangehrmlive.com/")
    time.sleep(3)
    driver.maximize_window()
    time.sleep(3)
    driver.find_element(By.NAME, value="username").send_keys("Admin")
    time.sleep(2)
    driver.find_element(By.NAME, value="password").send_keys("admin123")
    time.sleep(2)
    driver.find_element(By.XPATH, value="//button[@type='submit']").click()
    time.sleep(4)
    driver.find_element(By.LINK_TEXT,value="PIM").click()
    time.sleep(5)
    driver.find_element(By.LINK_TEXT, value="Employee List").click()
    time.sleep(5)
    driver.find_element(By.XPATH,value="(//i[@class='oxd-icon bi-pencil-fill'])[1]").click()
    time.sleep(5)
    driver.find_element(By.NAME, value="firstName").clear()
    time.sleep(5)
    driver.find_element(By.NAME, value="firstName").send_keys("Priyanka")
    time.sleep(5)
    driver.find_element(By.NAME, value="middleName").clear()
    time.sleep(3)
    driver.find_element(By.NAME, value="middleName").send_keys("Magesh")
    time.sleep(3)
    driver.find_element(By.NAME, value="lastName").clear()
    time.sleep(2)
    driver.find_element(By.NAME, value="lastName").send_keys("K")
    time.sleep(2)
    driver.find_element(By.XPATH,"(//button[@type='submit'])[1]").click()
    time.sleep(2)
    driver.find_element(By.XPATH,"(//button[@type='submit'])[2]").click()

def test_05():
    service = ChromeService(executable_path=ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    driver.get("https://opensource-demo.orangehrmlive.com/")
    time.sleep(3)
    driver.maximize_window()
    time.sleep(3)
    driver.find_element(By.NAME, value="username").send_keys("Admin")
    time.sleep(2)
    driver.find_element(By.NAME, value="password").send_keys("admin123")
    time.sleep(2)
    driver.find_element(By.XPATH, value="//button[@type='submit']").click()
    time.sleep(4)
    driver.find_element(By.LINK_TEXT,value="PIM").click()
    time.sleep(5)
    driver.find_element(By.LINK_TEXT, value="Employee List").click()
    time.sleep(5)
    driver.find_element(By.XPATH,value="(//i[@class='oxd-icon bi-trash'])[1]").click()
    time.sleep(5)
    driver.find_element(By.XPATH,value="//button[@class='oxd-button oxd-button--medium oxd-button--label-danger orangehrm-button-margin']").click()
    time.sleep(5)

